modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Uraneptus/ShimmerAndGlimmer/issues"

[[mods]] #mandatory
modId = "shimmerandglimmer" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile = "shimmerandglimmer_banner.png" #optional
authors = "Uraneptus" #optional
credits = "Assets by GoesBySully" #optional
displayURL = "https://github.com/Uraneptus/ShimmerAndGlimmer"
displayName = "Shimmer And Glimmer" #mandatory
description = '''
'''
displayTest = "MATCH_VERSION"

[[dependencies.shimmerandglimmer]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.shimmerandglimmer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[modproperties.shimmerandglimmer]
    catalogueImageIcon = "shimmerandglimmer_icon.png"